# Generated by Django 4.2.4 on 2023-08-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.TextField()),
                ('room', models.TextField()),
                ('strat_time', models.DateTimeField(verbose_name='date published')),
                ('end_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
